version: "3.3"

services:
  node:
    container_name: rentup_backend
    restart: always
    image: node:16.10.0
    ports:
      - 3005:3005
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - rentup_network

    #PRODUCTION
    command: bash -c "npm install && npm run start:prod"

    #DEVELOPMENT
    #command: bash -c "npm install && npm run dev

networks:
  rentup_network:
    driver: bridge